version: "3.9"

services:

  migration:
    build: .
    container_name: logistics_migration
    command: sh -c "python manage.py migrate --noinput"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - .env
    restart: "no"

  web:
    build: .
    container_name: logistics_backend
    entrypoint: ["/app/entrypoint.sh"]
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - .env
    expose:
      - "8000"
    depends_on:
      migration:
        condition: service_completed_successfully
    restart: always

  bot:
    build: .
    container_name: logistics_bot
    command: sh -c "python manage.py runbot"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./db.sqlite3:/app/db.sqlite3
    env_file:
      - .env
    depends_on:
      migration:
        condition: service_completed_successfully
    restart: always

  nginx:
    image: nginx:latest
    container_name: logistics_nginx
    ports:
      - "8888:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    restart: always

volumes:
  static_volume:
  media_volume:
