# Generated by Django 5.2.12 on 2026-03-17 10:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='driver',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['telegram_id'], name='drivers_dri_telegra_c3c79a_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['phone'], name='drivers_dri_phone_39e97b_idx'),
        ),
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['is_active'], name='drivers_dri_is_acti_7c5f39_idx'),
        ),
    ]
