# Generated by Django 5.2.12 on 2026-03-17 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_assigned_at_order_deleted_at_and_more'),
        ('payouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payout',
            unique_together={('order',)},
        ),
    ]
