# Generated by Django 5.2.12 on 2026-03-17 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsession',
            name='telegram_id',
            field=models.BigIntegerField(db_index=True, unique=True),
        ),
    ]
