# Generated by Django 5.2.12 on 2026-03-17 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('drivers', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_id', models.CharField(max_length=64, unique=True)),
                ('cargo_name', models.CharField(max_length=255)),
                ('cargo_description', models.TextField(blank=True)),
                ('cargo_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cargo_volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cargo_category', models.CharField(blank=True, max_length=100)),
                ('client_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('driver_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('current_status', models.CharField(choices=[('new', 'New'), ('client_confirmed', 'Client confirmed'), ('driver_search', 'Driver search'), ('driver_assigned', 'Driver assigned'), ('on_the_way_to_pickup', 'On the way to pickup'), ('at_pickup_location', 'At pickup location'), ('loaded', 'Loaded'), ('on_the_way_with_cargo', 'On the way with cargo'), ('at_dropoff_location', 'At dropoff location'), ('unloading_requested', 'Unloading requested'), ('unloading_confirmed', 'Unloading confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='new', max_length=64)),
                ('internal_comment', models.TextField(blank=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_reason', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('assigned_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='drivers.driver')),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='vehicles.vehicle')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.client')),
                ('created_by_dispatcher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('point_type', models.CharField(choices=[('pickup', 'Pickup'), ('waypoint', 'Waypoint'), ('dropoff', 'Dropoff')], max_length=16)),
                ('sequence', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=32)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='orders.order')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('old_status', models.CharField(blank=True, choices=[('new', 'New'), ('client_confirmed', 'Client confirmed'), ('driver_search', 'Driver search'), ('driver_assigned', 'Driver assigned'), ('on_the_way_to_pickup', 'On the way to pickup'), ('at_pickup_location', 'At pickup location'), ('loaded', 'Loaded'), ('on_the_way_with_cargo', 'On the way with cargo'), ('at_dropoff_location', 'At dropoff location'), ('unloading_requested', 'Unloading requested'), ('unloading_confirmed', 'Unloading confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=64, null=True)),
                ('new_status', models.CharField(choices=[('new', 'New'), ('client_confirmed', 'Client confirmed'), ('driver_search', 'Driver search'), ('driver_assigned', 'Driver assigned'), ('on_the_way_to_pickup', 'On the way to pickup'), ('at_pickup_location', 'At pickup location'), ('loaded', 'Loaded'), ('on_the_way_with_cargo', 'On the way with cargo'), ('at_dropoff_location', 'At dropoff location'), ('unloading_requested', 'Unloading requested'), ('unloading_confirmed', 'Unloading confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=64)),
                ('changed_by_system', models.BooleanField(default=False)),
                ('actor_role', models.CharField(blank=True, max_length=64)),
                ('comment', models.TextField(blank=True)),
                ('changed_by_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to='drivers.driver')),
                ('changed_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='proofs/')),
                ('file_type', models.CharField(blank=True, max_length=50)),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('proof_kind', models.CharField(choices=[('video', 'Video'), ('circle_video', 'Circle video'), ('image', 'Image'), ('document', 'Document')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='orders.order')),
                ('uploaded_by_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_proofs', to='drivers.driver')),
                ('uploaded_by_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_proofs', to=settings.AUTH_USER_MODEL)),
                ('status_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='orders.orderstatushistory')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
