# Generated by Django 5.2.12 on 2026-03-17 10:35

import orders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_deleted_at_client_is_deleted'),
        ('drivers', '0002_driver_card_last4_driver_deleted_at_and_more'),
        ('orders', '0001_initial'),
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_duration_minutes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='public_id',
            field=models.CharField(default=orders.models.generate_order_id, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='orderproof',
            name='file',
            field=models.FileField(upload_to='order_proofs/'),
        ),
        migrations.AlterUniqueTogether(
            name='orderpoint',
            unique_together={('order', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['current_status'], name='orders_orde_current_2761cc_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_orde_created_0e92de_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['assigned_driver'], name='orders_orde_assigne_4852f2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['client'], name='orders_orde_client__7a26db_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['order'], name='orders_orde_order_i_f43086_idx'),
        ),
        migrations.AddIndex(
            model_name='orderstatushistory',
            index=models.Index(fields=['new_status'], name='orders_orde_new_sta_58c5a2_idx'),
        ),
    ]
