# Generated by Django 5.2.12 on 2026-03-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('client', 'Client'), ('driver', 'Driver'), ('user', 'User')], max_length=16)),
                ('target_id', models.PositiveIntegerField()),
                ('channel', models.CharField(choices=[('telegram', 'Telegram'), ('crm', 'CRM')], max_length=16)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('related_order_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
